#!/bin/bash

# File to use
file=/etc/cron.d/sysstat

# Associative array of options for sa1
declare -A sa1
sa1[schedule]="*/10 * * * *"
sa1[user]="root"
sa1[path]="/usr/lib64/sa/sa1"
sa1[args]="-S DISK 1 1"

# Associative array of options for sa1
declare -A sa2
sa2[schedule]="53 23 * * *"
sa2[user]="root"
sa2[path]="/usr/lib64/sa/sa2"
sa2[args]="-A"

# Get our current working directory
cwd=$(dirname ${BASH_SOURCE[0]})

# Setup a path for binary tools (just in case)
PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

# Make sure our common libraries are available
if [ ! -f "${cwd}/libs/common" ] ; then
  echo "${prog}: Could not load libraries"
  exit 1
fi

# Load our libs
source ${cwd}/libs/common

# Displays available arg list
usage()
{
  cat <<EOF
Usage $0 [options]

Configure the SAR data collection

  Help:
    -h  Show this message
    -v  Enable verbosity mode

  Required:
    -a  Author name (required)

  Options:
    -f  File to use

  Validation:
    -c  Perform validation of change

  Restoration options:
    -r  Perform rollback of changes
    -i  Interactive mode, to be used with -r

  Development mode:
    -t  Run in test mode (assumes test env)

EOF
}

config_sysstat()
{
  # Error array
  errors=()

  # Global info array
  info=()

  # Use test suite if enabled
  if [ "${test}" == 1 ] ; then
    file=$(create_test "${cwd}/test/originals/$(basename ${file})")
    if [ $? != 0 ] ; then
      errors+=("ERROR: Error working with test env")
      echo "${errors[@]}" && return 1
    fi
  fi

  # Test for presence of file
  if [ ! -f ${file} ]; then
    errors+=("ERROR: File specified was not found,")
    echo "${errors[@]}" && return 1
  fi

  # Perform restoration if specified
  if [ "${restore}" == 1 ] ; then

    info+=("$(restore "${file}")")

    # Check results & return if an error occured
    if [ $? != 0 ]; then
      echo "${info[@]}" && return 1
    fi

    # Everything passed, return 0
    echo "${info[@]}" && return 0
  fi

  # Backup file if we are making changes
  if [[ "${check}" == 0 ]] && [[ "${restore}" == 0 ]] ; then

    info+=("$(backup "${file}" "${author}")")

    # Check results & return if an error occured
    if [ $? != 0 ]; then
      echo "${info[@]}" && return 1
    fi
  fi

  # Create ${pat1} based on ${sa1[@]}
  pat1="^$(echo "${sa1[schedule]}"|sed -e 's|\*|\\*|g' -e 's|\/|\\/|g').*${sa1[user]}.*${sa1[path]}.*${sa1[args]}"

  # Create ${rep1} based on ${sa1[@]}
  rep1="${sa1[schedule]}  ${sa1[user]}  ${sa1[path]} ${sa1[args]}"

  # Create ${pat2} based on ${sa2[@]}
  pat2="^$(echo "${sa2[schedule]}"|sed -e 's|\*|\\*|g' -e 's|\/|\\/|g').*${sa2[user]}.*${sa2[path]}.*${sa2[args]}"

  # Create ${rep1} based on ${sa1[@]}
  rep2="${sa2[schedule]}  ${sa2[user]}  ${sa2[path]} ${sa2[args]}"

  # Work if asked
  if [ "${check}" == 0 ]; then

    info+=("INFO: Applying settings for sa1,")
    str_replace "${file}" "${pat1}" "${rep1}"

    info+=("INFO: Applying settings for sa2,")
    str_replace "${file}" "${pat2}" "${rep2}"
  fi

  # Perform validation of ${rep2}
  info+=("INFO: Validating sa1,")
  chk1=$(grep "${pat1}" ${file})
  if [ "${chk1}" == "" ]; then
    errors+=("ERROR: Could not validate sa1,")
  fi

  # Perform validation of ${rep1}
  info+=("INFO: Validating sa2,")
  chk2=$(grep "${pat2}" ${file})
  if [ "${chk2}" == "" ]; then
    errors+=("ERROR: Could not validate sa2,")
  fi

  # Return errors
  if [ "${#errors[@]}" != 0 ] ; then
    errors+=("${info[@]}")
    echo "${errors[@]}" && return 1
  fi

  # Expose information array
  echo "${info[@]}"

  # Return code
  return 0
}

# Global options
verbose=0
check=0
restore=0
test=0
interactive=0
prog=$(basename $0)

# Ensure we have permissions
if [ $UID != 0 ] ; then
  echo "${prog}: Requires root privileges"
  exit 1
fi

# Set variables
while getopts "ha:vcrtif:" OPTION ; do
  case $OPTION in
    h) usage && exit 1 ;;
    a) author=$OPTARG ;;
    f) file=$OPTARG ;;
    v) verbose=1 ;;
    c) check=1 ;;
    r) restore=1 ;;
    t) test=1 ;;
    i) interactive=1 ;;
    ?) usage && exit 1 ;;
  esac
done

# Make sure we have an author if we are not restoring or validating
if [[ "${author}" == "" ]] && [[ "${restore}" == 0 ]] && [[ "${check}" == 0 ]]; then
  echo "${prog}: Must specify an author name (use -a <initials>)"
  usage
  exit 1
fi

# Robot, do work
main "config_sysstat"
