#!/bin/bash

# Default proxy ${proxy}
proxyuri=""

# RHN subscription tool
rhn=/usr/bin/subscription-manager

# Setup a path for binary tools (just in case)
PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

# Make sure our common libraries are available
if [ ! -f "libs/common" ] ; then
  echo "${prog}: Could not load libraries"
  exit 1
fi

# Load our libs
source libs/common

# Displays available arg list
usage()
{
  cat <<EOF
Usage $0 [options]

Auto register system with RHSM

  Help:
    -h  Show this message
    -v  Enable verbosity mode

  Options:
    -u  RHN username
    -p  RHN password
    -x  Proxy URI
    -y  Proxy username
    -z  Proxy password

EOF
}

proxy()
{
  # Build argument list based on passed options & register tool
  if [[ "${proxyuri}" != "" ]] && [[ "${proxyuser}" != "" ]] &&
      [[ "${proxypass}" != "" ]]; then

    # Set a local args list
    echo "--proxy=${proxyuri} --proxyuser=${proxyuser} --proxypass=${proxypass}"
  fi
}

register()
{
  # Error array
  errors=()

  # Global info array
  info=()

  # Build proxy args
  args=$(proxy)

  # Informational message
  info+=("INFO: Registering system with RHSM,")

  # Register system
  output=$(${rhn} register --force --auto-attach ${args} --username=${rhnuser} --password=${rhnpass})
  if [ $? -ne 0 ]; then
    errors+=("ERROR: An error occured with RHSM registration (${output}),")
  fi

  # Tear down proxy information if proxy options passed
  proxy_teardown

  # Return errors
  if [ "${#errors[@]}" != 0 ] ; then
    errors+=("${info[@]}")
    echo "${errors[@]}" && return 1
  fi

  # Expose information array
  echo "${info[@]}"

  # Return code
  return 0
}

# Global options
verbose=0
rhnuser=
rhnpass=
proxyuser=
proxypass=
prog=$(basename $0)

# Ensure we have permissions
if [ $UID != 0 ] ; then
  echo "${prog}: Requires root privileges"
  exit 1
fi

# Set variables
while getopts "hvu:p:x:y:z:" OPTION ; do
  case $OPTION in
    h) usage && exit 1 ;;
    u) rhnuser=$OPTARG ;;
    p) rhnpass=$OPTARG ;;
    x) proxyuri=$OPTARG ;;
    y) proxyuser=$OPTARG ;;
    z) proxypass=$OPTARG ;;
    v) verbose=1 ;;
    ?) usage && exit 1 ;;
  esac
done

# Make sure ${rhnuser} & ${rhnpass} are set
if [[ "${rhnuser}" == "" ]] || [[ "${rhnpass}" == "" ]]; then
  echo "${prog}: Must specify a rhn user & password"
  usage
  exit 1
fi

# Robot, do work
main "register"
